packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@apollo/client@*':
    dependencies:
      graphql: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs
